A-4
Pr-requisites:-
Knowledge about sed.
Knowledge about regular-exp.
Objectives: -

To learn sed command-line.
To learn about regular-exp.
Requirements: -

Pass a filename through command-line.
Delete all the empty lines from the input file and save it back.
If the line is empty with spaces or tabs you need to delete that line also.
Use sed command to delete the empty lines.
Contents of file.txt: (blank lines with multiple spaces)

Hello

         

How

               

are



you?

Sample execution: -
1. ./delete_empty_lines.sh file.txt
Empty lines are deleted
Hello
How
are
you?

2. ./delete_empty_lines.sh
Error: Please pass the file name through command line.